global:
  scrape_interval:     60s
  evaluation_interval: 120s
  external_labels:
      monitor: 'my-project'

rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets:
    - 192.168.0.61:8080
- job_name: 'node'
  static_configs:
  - targets:
    - 192.168.0.61:9100
    - 192.168.0.63:9100